name: gestao_clientes
description: Aplicativo de Gestão de Clientes
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  supabase_flutter: ^1.10.14
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  provider: ^6.0.5
  url_launcher: ^6.1.11
  shared_preferences: ^2.1.1
  flutter_masked_text2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 